//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ORDER_DETAIL_ID { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
