//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductStore = new HashSet<ProductStore>();
        }
    
        public int PRODUCT_INFO_ID { get; set; }
        public int COLOR_ID { get; set; }
        public double lenght { get; set; }
        public double width { get; set; }
        public double height { get; set; }
        public double weight { get; set; }
        public string name { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStore> ProductStore { get; set; }
    }
}
