//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStore()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int PRODUCT_ID { get; set; }
        public int STORE_ID { get; set; }
        public int PRODUCT_INFO_ID { get; set; }
        public int PRODUCT_TYPE_ID { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public int number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Store Store { get; set; }
    }
}
