//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAddress
    {
        public int ADDRESS_ID { get; set; }
        public Nullable<int> STORE_ID { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string building { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
